# Generated by Django 4.2.7 on 2024-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('situacaoentidade', models.IntegerField(blank=True, null=True)),
                ('cargo_id', models.IntegerField(blank=True, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contatos',
                'ordering': ('nome',),
            },
        ),
    ]
