# Generated by Django 4.2.3 on 2023-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, null=True, verbose_name='CPF'),
        ),
    ]
