# Generated by Django 4.2.7 on 2024-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField()),
                ('month', models.IntegerField()),
                ('ano', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('fixo', models.BooleanField()),
                ('situacaoentidade', models.IntegerField()),
                ('importado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'feriados',
                'ordering': ('descricao',),
            },
        ),
    ]
