# Generated by Django 4.2.7 on 2024-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
