version: '3.3'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5433:5433

  web-folha_ponto_on_docker:
    build: ./app
    environment:
      - DB_HOST=db
      - DB_USER=hello_django
      - DB_NAME=hello_django_dev
      - DB_PASSWORD=hello_django
      - REDIS_HOST=redis-folha_ponto_on_docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
      - 5676:5676
    env_file:
      - ./.env.dev
    depends_on:
      - db

networks:
  default:
    external:
      name: folha_ponto_on_docker
volumes:
  postgres_data:
