version: '3.3'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5433:5433
  redis-folha_ponto_on_docker:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6378:6378"
    entrypoint: redis-server --save 60 1  --loglevel warning
  web-folha_ponto_on_docker:
    build: ./app
    environment:
      - DB_HOST=db
      - DB_USER=hello_django
      - DB_NAME=hello_django_dev
      - DB_PASSWORD=hello_django
      - REDIS_HOST=redis-folha_ponto_on_docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
      - 5676:5676
    env_file:
      - ./.env.dev
    depends_on:
      - db

  celery-folha_ponto_on_docker:
    build: ./app
    environment:
      - DB_HOST=db
      - DB_USER=hello_django
      - DB_NAME=hello_django_dev
      - DB_PASSWORD=hello_django
      - REDIS_HOST=redis-folha_ponto_on_docker

    entrypoint: celery -A folha_ponto worker -l INFO -B -E -c 2
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
      - redis-folha_ponto_on_docker
      - web-folha_ponto_on_docker

  flower-folha_ponto_on_docker:
    build: ./app
    environment:
      - DB_HOST=db
      - DB_USER=hello_django
      - DB_NAME=hello_django_dev
      - DB_PASSWORD=hello_django
      - REDIS_HOST=redis-folha_ponto_on_docker

    entrypoint: celery -A folha_ponto flower
    ports:
      - "5558:5557"
    depends_on:
      - celery-folha_ponto_on_docker
      - redis-folha_ponto_on_docker
networks:
  default:
    external:
      name: folha_ponto_on_docker
volumes:
  postgres_data:
