# Generated by Django 4.2.7 on 2024-08-10 11:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_de_horas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoDeHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_apurado', models.DateField()),
                ('total_credor', models.DurationField(default=datetime.timedelta(0))),
                ('total_devedor', models.DurationField(default=datetime.timedelta(0))),
                ('saldo_anterior', models.DurationField(default=datetime.timedelta(0))),
                ('compensacao', models.DurationField(default=datetime.timedelta(0))),
                ('pagamento', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco de Horas',
                'verbose_name_plural': 'Bancos de Horas',
                'db_table': 'banco_de_horas',
                'ordering': ('-periodo_apurado', 'user'),
                'unique_together': {('user', 'periodo_apurado')},
            },
        ),
    ]
