# Generated by Django 4.2.7 on 2024-08-05 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_de_horas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valorinserido',
            unique_together={('user', 'competencia')},
        ),
    ]
