# Generated by Django 4.2.7 on 2024-08-11 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_de_horas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorInserido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('compensacao', models.DurationField(default=datetime.timedelta(0))),
                ('pagamento', models.DurationField(default=datetime.timedelta(0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valor Inserido',
                'verbose_name_plural': 'Valores Inseridos',
                'db_table': 'valor_inserido',
                'ordering': ('-competencia', 'user'),
                'unique_together': {('user', 'competencia')},
            },
        ),
    ]
