# Generated by Django 4.2.7 on 2024-05-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_horas', '0003_remove_bancodehoras_saldo_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancodehoras',
            old_name='valor_pago',
            new_name='pagamento',
        ),
    ]
