# Generated by Django 4.2.7 on 2024-05-21 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_horas', '0004_rename_valor_pago_bancodehoras_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancodehoras',
            options={'ordering': ('user', '-periodo_apurado'), 'verbose_name': 'Banco de Horas', 'verbose_name_plural': 'Bancos de Horas'},
        ),
        migrations.AddField(
            model_name='bancodehoras',
            name='compensacao',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
