# Generated by Django 4.2.7 on 2024-05-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_de_horas', '0005_alter_bancodehoras_options_bancodehoras_compensacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancodehoras',
            name='pagamento',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
