# Generated by Django 4.2.7 on 2024-10-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferias',
            options={'ordering': ['user', 'periodo', 'data_inicial'], 'verbose_name': 'Férias', 'verbose_name_plural': 'Férias'},
        ),
    ]
