# Generated by Django 4.2.7 on 2024-02-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ferias',
            table='ferias',
        ),
    ]
