# Generated by Django 4.2.7 on 2024-05-11 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_alter_ferias_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferias',
            options={'ordering': ['periodo', 'data_inicial'], 'verbose_name': 'Férias', 'verbose_name_plural': 'Férias'},
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_uteis',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
