# Generated by Django 4.2.7 on 2024-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tipodocumento', models.IntegerField(blank=True, null=True)),
                ('documento', models.BigIntegerField(blank=True, null=True)),
                ('nomerazao', models.CharField(max_length=100)),
                ('apelidofantazia', models.CharField(max_length=100)),
                ('tipocertificado', models.IntegerField(blank=True, null=True)),
                ('senhacertificado', models.CharField(blank=True, max_length=50, null=True)),
                ('vencimentocertificado', models.DateField(blank=True, null=True)),
                ('logositebv', models.BooleanField(blank=True, null=True)),
                ('iniciobv', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('codigosistema', models.CharField(blank=True, max_length=10, null=True)),
                ('situacaoentidade', models.IntegerField(blank=True, null=True)),
                ('codigoterceiro', models.CharField(blank=True, max_length=10, null=True)),
                ('controlarvencimentocertificado', models.BooleanField()),
                ('emiteboleto', models.BooleanField()),
                ('diavencimentoboleto', models.IntegerField(blank=True, null=True)),
                ('grupoeconomico_id', models.CharField(blank=True, max_length=10, null=True)),
                ('contato_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ('nomerazao',),
            },
        ),
    ]
