# Generated by Django 4.1.1 on 2024-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigoterceiro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grupoeconomico_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
