# Generated by Django 4.2.7 on 2024-08-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Senha',
                'verbose_name_plural': 'Tipos de Senha',
                'db_table': 'tiposenha',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='controlarvencimentocertificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='emiteboleto',
            field=models.BooleanField(default=False),
        ),
    ]
