# Generated by Django 4.2.7 on 2024-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_tiposenha_options_cliente_tipo_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='informacao_adicional',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
