# Generated by Django 4.2.7 on 2024-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_informacao_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_senha',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_senha',
            field=models.ManyToManyField(to='cliente.tiposenha'),
        ),
    ]
