# Generated by Django 4.2.7 on 2024-08-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_cliente_tipo_senha_cliente_tipo_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='informacao_adicional',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_senha',
        ),
        migrations.CreateModel(
            name='ClienteTipoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('informacao_adicional', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('tipo_senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tiposenha')),
            ],
            options={
                'verbose_name': 'Cliente Tipo Senha',
                'verbose_name_plural': 'Clientes Tipos Senhas',
                'db_table': 'cliente_tipo_senha',
            },
        ),
    ]
