# Generated by Django 4.2.7 on 2024-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_cliente_informacao_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_imobiliária',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Imobiliária'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nire',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIRE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tributacao_estadual',
            field=models.FloatField(blank=True, default=0.0, max_length=20, null=True, verbose_name='Tributação Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tributacao_federal',
            field=models.FloatField(blank=True, default=0.0, max_length=20, null=True, verbose_name='Tributação Federal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tributacao_municipal',
            field=models.FloatField(blank=True, default=0.0, max_length=20, null=True, verbose_name='Tributação Municipal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacaoentidade',
            field=models.IntegerField(blank=True, choices=[(1, 'Ativado'), (2, 'Desativado')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipodocumento',
            field=models.IntegerField(blank=True, choices=[(1, 'Cpf'), (2, 'Cnpj'), (4, 'Outros')], default=1, null=True),
        ),
    ]
