# Generated by Django 4.2.7 on 2024-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cliente_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposenha',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
