# Generated by Django 4.2.7 on 2024-10-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_tiposenha_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tributacao_estadual',
            field=models.CharField(blank=True, default=0.0, max_length=20, null=True, verbose_name='Tributação Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tributacao_federal',
            field=models.CharField(blank=True, default=0.0, max_length=20, null=True, verbose_name='Tributação Federal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tributacao_municipal',
            field=models.CharField(blank=True, default=0.0, max_length=20, null=True, verbose_name='Tributação Municipal'),
        ),
    ]
