# Generated by Django 4.2.7 on 2024-10-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_tributacao_estadual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tributacao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tributação Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tributacao_federal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tributação Federal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tributacao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tributação Municipal'),
        ),
    ]
