# Generated by Django 4.2.7 on 2024-10-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_clientetiposenha_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contato_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
