# Generated by Django 4.2.7 on 2024-10-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_remove_cliente_contato_id_cliente_contato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
