# Generated by Django 4.2.7 on 2024-10-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_remove_cliente_contato_id_cliente_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_aniversario',
            field=models.DateField(blank=True, null=True),
        ),
    ]
