# Generated by Django 4.2.7 on 2024-06-10 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReceita',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('recibo', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Receita',
                'verbose_name_plural': 'Tipos de Receitas',
                'db_table': 'tiporeceitas',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField()),
                ('primeiro', models.BooleanField(default=False)),
                ('segundo', models.BooleanField(default=False)),
                ('atraso', models.BooleanField(default=False, verbose_name='Atraso')),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('atrasoautorizado', models.BooleanField(default=False, verbose_name='Atraso Autorizado')),
                ('over_10_hours_authorization', models.BooleanField(db_index=True, default=False, verbose_name='Autorização de +10 horas de jornada')),
                ('cliente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('tipo_receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apontamento.tiporeceita')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
                'db_table': 'pontos',
                'ordering': ('entrada',),
            },
        ),
    ]
