# Generated by Django 4.2.3 on 2023-11-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
