# Generated by Django 4.2.7 on 2024-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0002_alter_ponto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='ajuste_autorizado',
            field=models.BooleanField(default=False, verbose_name='Ajuste Autorizado'),
        ),
    ]
