# Generated by Django 4.2.3 on 2023-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0002_rename_usuario_id_ponto_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReceita',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('recibo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Receita',
                'verbose_name_plural': 'Tipos de Receitas',
                'db_table': 'tiporeceitas',
                'ordering': ('descricao',),
            },
        ),
    ]
