# Generated by Django 4.2.3 on 2023-11-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0003_tiporeceita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='tiporeceita_id',
        ),
        migrations.AddField(
            model_name='ponto',
            name='tipo_receita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apontamento.tiporeceita'),
        ),
    ]
