# Generated by Django 4.2.7 on 2024-08-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0003_ponto_ajuste_autorizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='ajuste_autorizado',
            field=models.BooleanField(default=True, verbose_name='Ajuste Autorizado'),
        ),
    ]
