# Generated by Django 4.2.7 on 2024-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0004_alter_ponto_ajuste_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='ajuste',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ajuste'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='ajuste_autorizado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ajuste Autorizado'),
        ),
    ]
