# Generated by Django 4.2.7 on 2024-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0005_ponto_ajuste_alter_ponto_ajuste_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='status_ajuste',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendente'), (1, 'Autorizado'), (2, 'Negado')], db_index=True, default=0, verbose_name='Status do Ajuste'),
        ),
    ]
