# Generated by Django 4.2.3 on 2023-11-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0005_remove_ponto_cliente_id_ponto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo_receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apontamento.tiporeceita'),
        ),
    ]
