# Generated by Django 4.2.3 on 2023-11-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0006_alter_ponto_tipo_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
