# Generated by Django 4.1.1 on 2023-11-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('apontamento', '0007_rename_cliente_ponto_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='atraso',
            field=models.BooleanField(default=False, verbose_name='Atraso'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='atrasoautorizado',
            field=models.BooleanField(default=False, verbose_name='Atraso Autorizado'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
