# Generated by Django 4.1.1 on 2024-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0008_alter_ponto_atraso_alter_ponto_atrasoautorizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeceita',
            name='recibo',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3),
        ),
        migrations.AlterField(
            model_name='tiporeceita',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
    ]
