# Generated by Django 4.2.7 on 2024-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0009_alter_tiporeceita_recibo_alter_tiporeceita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='over_10_hours_authorization',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Autorização de +10 horas de jornada'),
        ),
    ]
