# Generated by Django 4.2.7 on 2024-06-10 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, default='', help_text='Nome do Departamento', max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacaoentidade', models.IntegerField(blank=True, default=0, help_text='Situação Entidade', null=True)),
                ('contato_id', models.IntegerField(blank=True, default=0, help_text='Informe o Contato', null=True)),
                ('bateponto', models.CharField(blank=True, default='Sim', help_text='Marque se bate ponto.', max_length=3, null=True, verbose_name=(('Não', 'Não'), ('Sim', 'Sim')))),
                ('cargahoraria', models.IntegerField(blank=True, default=8, null=True)),
                ('semintervaloalmoco', models.CharField(blank=True, default='Sim', help_text='Marque se não tiver intervalo para almoço.', max_length=10, null=True, verbose_name=(('Não', 'Não'), ('Sim', 'Sim')))),
                ('nome', models.CharField(blank=True, db_index=True, default='', help_text='Informe seu Nome em até 20 posições', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, default='', help_text='Informe seu E-mail', max_length=100, null=True)),
                ('almoco', models.CharField(blank=True, default='Não Almoça', help_text='Informe rotina do almoço', max_length=10, null=True, verbose_name=(('TODO DIA', 'Todo Dia'), ('NÃO ALMOÇA', 'Não Almoça'), ('EVENTUAL', 'Eventual')))),
                ('departamento', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departamento')),
                ('tipo_receita', models.ForeignKey(blank=True, help_text='Escolha o Tipo de Receita mais utilizado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='apontamento.tiporeceita')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'userprofiles',
                'ordering': ('user',),
            },
        ),
    ]
