# Generated by Django 4.2.3 on 2023-11-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacaoentidade', models.IntegerField()),
                ('contato_id', models.IntegerField()),
                ('bateponto', models.BooleanField()),
                ('cargahoraria', models.IntegerField(default=0)), #changed timefield(default=00:00:00) to integerfield(default=0).
                ('departamento', models.IntegerField(default=0)),
                ('semintervaloalmoco', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
                'db_table': 'userprofiles',
                'ordering': ('user',),
            },
        ),
    ]
