# Generated by Django 4.2.7 on 2024-05-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0010_ponto_over_10_hours_authorization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, default='', help_text='Nome do Departamento', max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user',), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='almoco',
            field=models.CharField(blank=True, default='Não Almoça', help_text='Informe rotina do almoço', max_length=10, null=True, verbose_name=(('TODO DIA', 'Todo Dia'), ('NÃO ALMOÇA', 'Não Almoça'), ('EVENTUAL', 'Eventual'))),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Informe seu E-mail', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Informe seu Nome em até 20 posições', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_receita',
            field=models.ForeignKey(blank=True, help_text='Escolha o Tipo de Receita mais utilizado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='apontamento.tiporeceita'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bateponto',
            field=models.CharField(blank=True, default='Sim', help_text='Marque se bate ponto.', max_length=3, null=True, verbose_name=(('Não', 'Não'), ('Sim', 'Sim'))),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cargahoraria',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contato_id',
            field=models.IntegerField(blank=True, default=0, help_text='Informe o Contato', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semintervaloalmoco',
            field=models.CharField(blank=True, default='Sim', help_text='Marque se não tiver intervalo para almoço.', max_length=10, null=True, verbose_name=(('Não', 'Não'), ('Sim', 'Sim'))),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='situacaoentidade',
            field=models.IntegerField(blank=True, default=0, help_text='Situação Entidade', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='departamento',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.departamento'),
        ),
    ]
