# Generated by Django 4.2.7 on 2024-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='almoco',
            field=models.CharField(blank=True, choices=[('TODO DIA', 'Todo Dia'), ('NÃO ALMOÇA', 'Não Almoça'), ('EVENTUAL', 'Eventual')], default='Não Almoça', help_text='Informe rotina do almoço', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bateponto',
            field=models.CharField(blank=True, choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', help_text='Marque se bate ponto.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semintervaloalmoco',
            field=models.CharField(blank=True, choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', help_text='Marque se não tiver intervalo para almoço.', max_length=10, null=True),
        ),
    ]
