# Generated by Django 4.2.7 on 2024-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='consumo',
            field=models.BooleanField(default=True),
        ),
    ]
