# Generated by Django 4.2.7 on 2024-04-29 21:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refeicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refeicao',
            unique_together={('usuario', 'data_refeicao')},
        ),
    ]
